In [2]:
from numpy.random import default_rng
from random import randrange
import numpy as np

rng = default_rng()
pattern = rng.choice(2, (10,10))
print(pattern)

[[1 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 1 1]
 [1 0 1 0 1 1 0 0 1 0]
 [0 1 0 0 1 1 1 1 0 1]
 [1 0 1 0 1 0 0 0 0 1]
 [1 1 1 0 0 0 0 0 0 0]
 [1 0 0 0 1 1 1 1 1 0]
 [0 0 1 0 0 0 0 1 0 0]
 [1 1 1 1 1 1 0 1 1 1]
 [1 1 1 1 0 1 0 1 1 0]]


In [3]:
indices = np.argwhere(pattern==True)
print(indices)

[[0 0]
 [0 4]
 [1 5]
 [1 8]
 [1 9]
 [2 0]
 [2 2]
 [2 4]
 [2 5]
 [2 8]
 [3 1]
 [3 4]
 [3 5]
 [3 6]
 [3 7]
 [3 9]
 [4 0]
 [4 2]
 [4 4]
 [4 9]
 [5 0]
 [5 1]
 [5 2]
 [6 0]
 [6 4]
 [6 5]
 [6 6]
 [6 7]
 [6 8]
 [7 2]
 [7 7]
 [8 0]
 [8 1]
 [8 2]
 [8 3]
 [8 4]
 [8 5]
 [8 7]
 [8 8]
 [8 9]
 [9 0]
 [9 1]
 [9 2]
 [9 3]
 [9 5]
 [9 7]
 [9 8]]


In [7]:
num_neighbor = 1
index = indices[1]

left = max(0,index[0]-num_neighbor)
right = max(0,index[0]+num_neighbor+1)

bottom = max(0,index[1]-num_neighbor)
top = max(0,index[1]+num_neighbor+1)

neighbors = pattern[left:right,bottom:top]
print(neighbors)

[[0 1 0]
 [0 0 1]]


In [11]:
print(neighbors[1,2])

1


In [8]:
indexes = np.argwhere(neighbors == True)
print(indexes)

[[0 1]
 [1 2]]


In [89]:
_,count = np.unique(neighbors, return_counts=True)
count[1] = count[1] - 1
print(count)

[1 4]


In [90]:
if count[1] < 2:
    pattern[index[0],index[1]] = False
if count[1] > 3:
    pattern[index[0],index[1]] = False

print(pattern)

[[0 0 1 0 0 1 0 0 1 0]
 [1 0 1 1 1 1 1 1 0 1]
 [0 0 0 0 1 0 1 0 0 1]
 [0 0 0 0 0 1 0 1 1 1]
 [0 1 0 1 1 0 1 0 1 0]
 [1 0 0 0 0 1 0 1 1 1]
 [1 0 0 0 1 0 0 1 0 0]
 [0 0 1 0 0 1 0 1 1 1]
 [1 1 0 0 0 0 1 1 1 1]
 [0 1 1 0 0 0 1 1 1 0]]
